services:
  postgres:
    image: postgres:16
    container_name: task-manager-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - task_manager_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d task_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: task-manager-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ISSUER_URI: http://localhost:${KEYCLOAK_PORT}/realms/task-manager
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/task-manager/protocol/openid-connect/certs
    ports:
      - "${BACKEND_PORT}:8080"
  
  frontend:
    build: ./frontend
    container_name: task-manager-web
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_KEYCLOAK_URL: http://localhost:${KEYCLOAK_PORT}
      VITE_KEYCLOAK_REALM: task-manager
      VITE_KEYCLOAK_CLIENT_ID: task-manager-web
    ports:
      - "${FRONTEND_PORT}:5173"
  
  keycloak-db:
    image: postgres:16
    container_name: task-manager-keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    container_name: task-manager-keycloak
    restart: always
    command: start-dev --import-realm
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: http://localhost:${KEYCLOAK_PORT}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro

volumes:
  task_manager_data:
  keycloak_data: