spring.application.name=task-manager-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true